# Generated by Django 3.1.2 on 2020-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='point_title',
            field=models.CharField(default='test', help_text='При наведении курсором на точку будет отображаться это название.', max_length=100, verbose_name='Название точки'),
            preserve_default=False,
        ),
    ]
