# Generated by Django 3.1.2 on 2020-10-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20201018_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Долгота'),
        ),
    ]
